steps:
  # Step 1: Build the application with Maven
  - name: maven:3.8-openjdk-17
    entrypoint: mvn
    args: ['clean', 'package', '-DskipTests', '-Dspotless.check.skip=true']
  
  # Step 2: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '--no-cache', '-t', 'gcr.io/sublime-scion-464620-c5/sas-dhop-site', '.']
  
  # Step 3: Push the container image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/sublime-scion-464620-c5/sas-dhop-site']
  
  # Step 4: Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'sas-dhop-site'
      - '--image'
      - 'gcr.io/sublime-scion-464620-c5/sas-dhop-site'
      - '--platform'
      - 'managed'
      - '--region'
      - 'asia-southeast1'
      - '--allow-unauthenticated'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '2'
      - '--port'
      - '8080'
      - '--timeout'
      - '300s'
      - '--set-env-vars'

# Images to be stored in Google Container Registry
images:
  - 'gcr.io/sublime-scion-464620-c5/sas-dhop-site'

# Set a longer timeout for the build
timeout: 1800s 