services:
  db:
    env_file:
      - .env
    image: mysql:8.0
    container_name: DHop-Database
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=exe201
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: