package com.sas.dhop.site.model.enums;

public enum BookingStatus {
  BOOKING_PENDING,
  BOOKING_ACCEPTED,
  BOOKING_IN_PROGRESS,
  BOOKING_WORKING_DONE,
  BOOKING_COMPLETED,
  BOOKING_END,
  BOOKING_INACTIVATE
}
