CREATE TABLE `booking` (
                           `id` int NOT NULL AUTO_INCREMENT,
                           `customer_id` int NOT NULL,
                           `dancer_id` int DEFAULT NULL,
                           `choreography_id` int DEFAULT NULL,
                           `area_id` int NOT NULL,
                           `status_id` int NOT NULL,
                           `booking_date` datetime DEFAULT NULL,
                           `start_time` datetime DEFAULT NULL,
                           `end_time` datetime DEFAULT NULL,
                           `address` varchar(255) DEFAULT NULL,
                           `detail` text,
                           `update_booking_date` datetime DEFAULT NULL,
                           `booking_status` varchar(255) DEFAULT NULL,
                           `customer_phone` varchar(255) DEFAULT NULL,
                           `number_of_training_sessions` int DEFAULT NULL,
                           `dancer_phone` varchar(255) DEFAULT NULL,
                           `choreography_phone` varchar(255) DEFAULT NULL,
                           `cancel_reason` varchar(255) DEFAULT NULL,
                           `cancel_person_name` varchar(255) DEFAULT NULL,
                           `price` decimal(38,2) DEFAULT NULL,
                           `dancer_account_number` varchar(255) DEFAULT NULL,
                           `dancer_bank` varchar(255) DEFAULT NULL,
                           `choreography_account_number` varchar(255) DEFAULT NULL,
                           `choreography_bank` varchar(255) DEFAULT NULL,
                           `created_at` datetime(6) DEFAULT NULL,
                           `updated_at` datetime(6) DEFAULT NULL,
                           `number_of_team_member` int DEFAULT NULL,
                           PRIMARY KEY (`id`),
                           KEY `customer_id` (`customer_id`),
                           KEY `dancer_id` (`dancer_id`),
                           KEY `choreography_id` (`choreography_id`),
                           KEY `area_id` (`area_id`),
                           KEY `status_id` (`status_id`),
                           CONSTRAINT `booking_ibfk_1` FOREIGN KEY (`customer_id`) REFERENCES `users` (`id`),
                           CONSTRAINT `booking_ibfk_2` FOREIGN KEY (`dancer_id`) REFERENCES `dancer` (`id`),
                           CONSTRAINT `booking_ibfk_3` FOREIGN KEY (`choreography_id`) REFERENCES `choreography` (`id`),
                           CONSTRAINT `booking_ibfk_5` FOREIGN KEY (`area_id`) REFERENCES `area` (`id`),
                           CONSTRAINT `booking_ibfk_6` FOREIGN KEY (`status_id`) REFERENCES `status` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;