name: Build and Publish Monolith Docker Image

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

jobs:
  build:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Make Maven wrapper executable
        run: chmod +x mvnw

      - name: Spotless apply
        run: ./mvnw spotless:apply

      - name: Build with Maven (skip tests)
        run: ./mvnw clean install -DskipTests

      - name: Build Docker image
        run: ./mvnw spring-boot:build-image -DskipTests

      - name: Login to Docker Hub
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker image to Docker Hub
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/sas.dhop.site.be  # Đẩy image lên Docker Hub
          echo "Docker image pushed to Docker Hub."
